// <auto-generated />
using Assignment2_Week3_Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment2_Week3_Data.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2_Week3_Data.Entities.Commune", b =>
                {
                    b.Property<int>("CommuneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommuneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.HasKey("CommuneId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Communes");

                    b.HasData(
                        new
                        {
                            CommuneId = 1,
                            CommuneName = "Đồng Than",
                            DistrictId = 1
                        },
                        new
                        {
                            CommuneId = 2,
                            CommuneName = "Tân Lập",
                            DistrictId = 1
                        },
                        new
                        {
                            CommuneId = 3,
                            CommuneName = "Trung Hưng",
                            DistrictId = 1
                        },
                        new
                        {
                            CommuneId = 4,
                            CommuneName = "Chí Tân",
                            DistrictId = 2
                        },
                        new
                        {
                            CommuneId = 5,
                            CommuneName = "Dạ Trạch",
                            DistrictId = 2
                        },
                        new
                        {
                            CommuneId = 6,
                            CommuneName = "Đại Tập",
                            DistrictId = 2
                        },
                        new
                        {
                            CommuneId = 7,
                            CommuneName = "An Viên",
                            DistrictId = 3
                        },
                        new
                        {
                            CommuneId = 8,
                            CommuneName = "Cương Chính",
                            DistrictId = 3
                        },
                        new
                        {
                            CommuneId = 9,
                            CommuneName = "Dị Chế",
                            DistrictId = 3
                        },
                        new
                        {
                            CommuneId = 10,
                            CommuneName = "Bồng Khê",
                            DistrictId = 4
                        },
                        new
                        {
                            CommuneId = 11,
                            CommuneName = "Chi Khê",
                            DistrictId = 4
                        },
                        new
                        {
                            CommuneId = 12,
                            CommuneName = "Đôn Phục",
                            DistrictId = 4
                        },
                        new
                        {
                            CommuneId = 13,
                            CommuneName = "Bài Sơn",
                            DistrictId = 5
                        },
                        new
                        {
                            CommuneId = 14,
                            CommuneName = "Đà Sơn",
                            DistrictId = 5
                        },
                        new
                        {
                            CommuneId = 15,
                            CommuneName = "Đặng Sơn",
                            DistrictId = 5
                        },
                        new
                        {
                            CommuneId = 16,
                            CommuneName = "Châu Nhân",
                            DistrictId = 6
                        },
                        new
                        {
                            CommuneId = 17,
                            CommuneName = "Hưng Lĩnh",
                            DistrictId = 6
                        },
                        new
                        {
                            CommuneId = 18,
                            CommuneName = "Hưng Tây",
                            DistrictId = 6
                        },
                        new
                        {
                            CommuneId = 19,
                            CommuneName = "Ái Thượng",
                            DistrictId = 7
                        },
                        new
                        {
                            CommuneId = 20,
                            CommuneName = "Ban Công",
                            DistrictId = 7
                        },
                        new
                        {
                            CommuneId = 21,
                            CommuneName = "Cành Nàng",
                            DistrictId = 7
                        },
                        new
                        {
                            CommuneId = 22,
                            CommuneName = "Cẩm Long",
                            DistrictId = 8
                        },
                        new
                        {
                            CommuneId = 23,
                            CommuneName = "Cẩm Lương",
                            DistrictId = 8
                        },
                        new
                        {
                            CommuneId = 24,
                            CommuneName = "Cẩm Quý",
                            DistrictId = 8
                        },
                        new
                        {
                            CommuneId = 25,
                            CommuneName = "Đông Thịnh",
                            DistrictId = 9
                        },
                        new
                        {
                            CommuneId = 26,
                            CommuneName = "Đông Văn",
                            DistrictId = 9
                        },
                        new
                        {
                            CommuneId = 27,
                            CommuneName = "Đông Sơn",
                            DistrictId = 9
                        });
                });

            modelBuilder.Entity("Assignment2_Week3_Data.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            DistrictName = "Yên Mỹ",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 2,
                            DistrictName = "Khoái Châu",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 3,
                            DistrictName = "Tiên Lữ",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 4,
                            DistrictName = "Con Cuông",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 5,
                            DistrictName = "Đô Lương",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 6,
                            DistrictName = "Hưng Nguyên",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 7,
                            DistrictName = "Bá Thước",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 8,
                            DistrictName = "Cẩm Thủy",
                            ProvinceId = 3
                        },
                        new
                        {
                            DistrictId = 9,
                            DistrictName = "Đông Sơn",
                            ProvinceId = 3
                        });
                });

            modelBuilder.Entity("Assignment2_Week3_Data.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            ProvinceName = "Hưng Yên"
                        },
                        new
                        {
                            ProvinceId = 2,
                            ProvinceName = "Nghệ An"
                        },
                        new
                        {
                            ProvinceId = 3,
                            ProvinceName = "Thanh Hóa"
                        });
                });

            modelBuilder.Entity("Assignment2_Week3_Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommuneId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("Yob")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Assignment2_Week3_Data.Entities.Commune", b =>
                {
                    b.HasOne("Assignment2_Week3_Data.Entities.District", "District")
                        .WithMany("Communes")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment2_Week3_Data.Entities.District", b =>
                {
                    b.HasOne("Assignment2_Week3_Data.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
